
services:
  app:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: 6.3.*
    container_name: 5_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - symfony_network
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: 5_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  nginx:
    image: nginx:alpine
    container_name: 5_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge